### ISSUE TITLE
strategy-factories › get-ipfs-tokenuri › extractor_test › get-ipfs-tokenuri extractor is timing out in CI

### ISSUE THREAD

**Issue by TimDaub** [neume-network/strategies#264] opened 2022-09-06 15:48 UTC
- https://github.com/neume-network/strategies/runs/8210904481?check_suite_focus=true
- it doesn't happen on my local machine so I wonder if it is a configuration or network issue

**Comment by TimDaub** [comment] 2022-09-06 15:48
@il3ven as you're the author of this test

**Comment by il3ven** [comment] 2022-09-22 21:47
Closing as duplicate of #280

**Closed by il3ven** 2022-09-22 21:47 UTC
